"""add_investor_scoring_fields

Revision ID: 40f382a72f21
Revises: 001
Create Date: 2026-01-05 11:32:58.195885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40f382a72f21'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_metrics_daily', sa.Column('reviews_7d', sa.Integer(), nullable=True))
    op.add_column('game_metrics_daily', sa.Column('reviews_30d', sa.Integer(), nullable=True))
    op.add_column('game_metrics_daily', sa.Column('review_velocity_7d', sa.Float(), nullable=True))
    op.add_column('game_metrics_daily', sa.Column('momentum_ratio', sa.Float(), nullable=True))
    op.add_column('game_metrics_daily', sa.Column('wishlists', sa.Integer(), nullable=True))
    op.add_column('game_metrics_daily', sa.Column('extras', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('game_metrics_daily', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('NOW()')))
    op.alter_column('game_metrics_daily', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('game_metrics_daily', 'reviews_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_game_metrics_date'), table_name='game_metrics_daily')
    op.drop_constraint(op.f('uix_game_metrics_game_date'), 'game_metrics_daily', type_='unique')
    op.create_index(op.f('ix_game_metrics_daily_date'), 'game_metrics_daily', ['date'], unique=False)
    op.create_index(op.f('ix_game_metrics_daily_game_id'), 'game_metrics_daily', ['game_id'], unique=False)
    op.create_unique_constraint('uq_game_metrics_daily_game_id_date', 'game_metrics_daily', ['game_id', 'date'])
    op.drop_constraint(op.f('game_metrics_daily_game_id_fkey'), 'game_metrics_daily', type_='foreignkey')
    op.create_foreign_key(None, 'game_metrics_daily', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_column('game_metrics_daily', 'rating_percent')
    op.drop_column('game_metrics_daily', 'reviews_recent')
    op.drop_column('game_metrics_daily', 'rank_signal')
    op.add_column('games', sa.Column('title', sa.String(length=256), nullable=False, server_default=''))
    op.add_column('games', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('has_demo', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('games', sa.Column('release_status', sa.String(length=32), nullable=False, server_default='unknown'))
    op.alter_column('games', 'source',
               existing_type=postgresql.ENUM('steam', 'itch', name='gamesource'),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('games', 'source_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('games', 'url',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.alter_column('games', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('games', 'price_eur',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_games_created_at', table_name='games')
    op.drop_constraint('uix_game_source_id', 'games', type_='unique')
    op.create_index(op.f('ix_games_source_id'), 'games', ['source_id'], unique=False)
    op.create_unique_constraint('uq_games_source_source_id', 'games', ['source', 'source_id'])
    op.drop_column('games', 'short_description')
    op.drop_column('games', 'currency')
    op.drop_column('games', 'release_date')
    op.drop_column('games', 'name')
    op.add_column('pitch_scores', sa.Column('score', sa.Float(), nullable=False, server_default='0'))
    op.add_column('pitch_scores', sa.Column('explanation', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('pitch_scores', sa.Column('breakdown', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('pitch_scores', sa.Column('product_potential', sa.Float(), nullable=True))
    op.add_column('pitch_scores', sa.Column('product_confidence', sa.String(length=16), nullable=True))
    op.add_column('pitch_scores', sa.Column('gtm_execution', sa.Float(), nullable=True))
    op.add_column('pitch_scores', sa.Column('gtm_confidence', sa.String(length=16), nullable=True))
    op.add_column('pitch_scores', sa.Column('team_delivery', sa.Float(), nullable=True))
    op.add_column('pitch_scores', sa.Column('team_confidence', sa.String(length=16), nullable=True))
    op.add_column('pitch_scores', sa.Column('potential_gap', sa.Float(), nullable=True))
    op.add_column('pitch_scores', sa.Column('fixability_score', sa.Float(), nullable=True))
    op.add_column('pitch_scores', sa.Column('investment_profile', sa.String(length=32), nullable=True))
    op.alter_column('pitch_scores', 'verdict',
               existing_type=postgresql.ENUM('PASS', 'WATCH', 'TALK', 'INVEST', name='verdict'),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_index('ix_pitch_scores_verdict', table_name='pitch_scores')
    op.drop_constraint('pitch_scores_pitch_id_key', 'pitch_scores', type_='unique')
    op.create_index('idx_fixability_score', 'pitch_scores', ['fixability_score'], unique=False)
    op.create_index('idx_investment_profile', 'pitch_scores', ['investment_profile'], unique=False)
    op.create_index('idx_potential_gap', 'pitch_scores', ['potential_gap'], unique=False)
    op.create_index(op.f('ix_pitch_scores_pitch_id'), 'pitch_scores', ['pitch_id'], unique=False)
    op.create_unique_constraint('uq_pitch_scores_pitch_id_created_at', 'pitch_scores', ['pitch_id', 'created_at'])
    op.drop_constraint('pitch_scores_pitch_id_fkey', 'pitch_scores', type_='foreignkey')
    op.create_foreign_key(None, 'pitch_scores', 'pitches', ['pitch_id'], ['id'], ondelete='CASCADE')
    op.drop_column('pitch_scores', 'score_steam')
    op.drop_column('pitch_scores', 'score_team')
    op.drop_column('pitch_scores', 'why_yes')
    op.drop_column('pitch_scores', 'score_market')
    op.drop_column('pitch_scores', 'score_total')
    op.drop_column('pitch_scores', 'next_step')
    op.drop_column('pitch_scores', 'score_asymmetry')
    op.drop_column('pitch_scores', 'why_no')
    op.drop_column('pitch_scores', 'updated_at')
    op.drop_column('pitch_scores', 'score_hook')
    op.drop_column('pitch_scores', 'comparables')
    op.add_column('pitches', sa.Column('score', sa.Float(), nullable=True))
    op.alter_column('pitches', 'dev_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('pitches', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('pitches', 'studio_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('pitches', 'hook_one_liner',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=512),
               nullable=False)
    op.alter_column('pitches', 'links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('pitches', 'build_link',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('pitches', 'video_link',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('pitches', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('pitches', 'status',
               existing_type=postgresql.ENUM('new', 'scored', 'reviewed', name='pitchstatus'),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_index('ix_pitches_created_at', table_name='pitches')
    op.drop_index('ix_pitches_status', table_name='pitches')
    op.add_column('trends_daily', sa.Column('source', sa.String(length=32), nullable=False, server_default=''))
    op.add_column('trends_daily', sa.Column('payload', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('trends_daily', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('NOW()')))
    op.alter_column('trends_daily', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('ix_trends_date_signal', table_name='trends_daily')
    op.drop_index('ix_trends_velocity', table_name='trends_daily')
    op.create_index(op.f('ix_trends_daily_date'), 'trends_daily', ['date'], unique=False)
    op.create_index(op.f('ix_trends_daily_source'), 'trends_daily', ['source'], unique=False)
    op.create_unique_constraint('uq_trends_daily_date_source', 'trends_daily', ['date', 'source'])
    op.drop_column('trends_daily', 'count')
    op.drop_column('trends_daily', 'signal')
    op.drop_column('trends_daily', 'signal_type')
    op.drop_column('trends_daily', 'velocity')
    op.drop_column('trends_daily', 'delta_7d')
    op.drop_column('trends_daily', 'avg_7d')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends_daily', sa.Column('avg_7d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trends_daily', sa.Column('delta_7d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trends_daily', sa.Column('velocity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trends_daily', sa.Column('signal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('trends_daily', sa.Column('signal', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('trends_daily', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_trends_daily_date_source', 'trends_daily', type_='unique')
    op.drop_index(op.f('ix_trends_daily_source'), table_name='trends_daily')
    op.drop_index(op.f('ix_trends_daily_date'), table_name='trends_daily')
    op.create_index('ix_trends_velocity', 'trends_daily', ['velocity'], unique=False)
    op.create_index('ix_trends_date_signal', 'trends_daily', ['date', 'signal'], unique=False)
    op.alter_column('trends_daily', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('trends_daily', 'created_at')
    op.drop_column('trends_daily', 'payload')
    op.drop_column('trends_daily', 'source')
    op.create_index('ix_pitches_status', 'pitches', ['status'], unique=False)
    op.create_index('ix_pitches_created_at', 'pitches', ['created_at'], unique=False)
    op.alter_column('pitches', 'status',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('new', 'scored', 'reviewed', name='pitchstatus'),
               existing_nullable=False)
    op.alter_column('pitches', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('pitches', 'video_link',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('pitches', 'build_link',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('pitches', 'links',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('pitches', 'hook_one_liner',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('pitches', 'studio_name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('pitches', 'email',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('pitches', 'dev_name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('pitches', 'score')
    op.add_column('pitch_scores', sa.Column('comparables', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('pitch_scores', sa.Column('score_hook', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pitch_scores', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('pitch_scores', sa.Column('why_no', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pitch_scores', sa.Column('score_asymmetry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pitch_scores', sa.Column('next_step', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('pitch_scores', sa.Column('score_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pitch_scores', sa.Column('score_market', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pitch_scores', sa.Column('why_yes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pitch_scores', sa.Column('score_team', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pitch_scores', sa.Column('score_steam', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch_scores', type_='foreignkey')
    op.create_foreign_key('pitch_scores_pitch_id_fkey', 'pitch_scores', 'pitches', ['pitch_id'], ['id'])
    op.drop_constraint('uq_pitch_scores_pitch_id_created_at', 'pitch_scores', type_='unique')
    op.drop_index(op.f('ix_pitch_scores_pitch_id'), table_name='pitch_scores')
    op.drop_index('idx_potential_gap', table_name='pitch_scores')
    op.drop_index('idx_investment_profile', table_name='pitch_scores')
    op.drop_index('idx_fixability_score', table_name='pitch_scores')
    op.create_unique_constraint('pitch_scores_pitch_id_key', 'pitch_scores', ['pitch_id'])
    op.create_index('ix_pitch_scores_verdict', 'pitch_scores', ['verdict'], unique=False)
    op.alter_column('pitch_scores', 'verdict',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('PASS', 'WATCH', 'TALK', 'INVEST', name='verdict'),
               existing_nullable=False)
    op.drop_column('pitch_scores', 'investment_profile')
    op.drop_column('pitch_scores', 'fixability_score')
    op.drop_column('pitch_scores', 'potential_gap')
    op.drop_column('pitch_scores', 'team_confidence')
    op.drop_column('pitch_scores', 'team_delivery')
    op.drop_column('pitch_scores', 'gtm_confidence')
    op.drop_column('pitch_scores', 'gtm_execution')
    op.drop_column('pitch_scores', 'product_confidence')
    op.drop_column('pitch_scores', 'product_potential')
    op.drop_column('pitch_scores', 'breakdown')
    op.drop_column('pitch_scores', 'explanation')
    op.drop_column('pitch_scores', 'score')
    op.add_column('games', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('short_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_games_source_source_id', 'games', type_='unique')
    op.drop_index(op.f('ix_games_source_id'), table_name='games')
    op.create_unique_constraint('uix_game_source_id', 'games', ['source_id'])
    op.create_index('ix_games_created_at', 'games', ['created_at'], unique=False)
    op.alter_column('games', 'price_eur',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('games', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('games', 'url',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('games', 'source_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('games', 'source',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('steam', 'itch', name='gamesource'),
               existing_nullable=False)
    op.drop_column('games', 'release_status')
    op.drop_column('games', 'has_demo')
    op.drop_column('games', 'description')
    op.drop_column('games', 'title')
    op.add_column('game_metrics_daily', sa.Column('rank_signal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('game_metrics_daily', sa.Column('reviews_recent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game_metrics_daily', sa.Column('rating_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game_metrics_daily', type_='foreignkey')
    op.create_foreign_key('game_metrics_daily_game_id_fkey', 'game_metrics_daily', 'games', ['game_id'], ['id'])
    op.drop_constraint('uq_game_metrics_daily_game_id_date', 'game_metrics_daily', type_='unique')
    op.drop_index(op.f('ix_game_metrics_daily_game_id'), table_name='game_metrics_daily')
    op.drop_index(op.f('ix_game_metrics_daily_date'), table_name='game_metrics_daily')
    op.create_unique_constraint('uix_game_metrics_game_date', 'game_metrics_daily', ['game_id', 'date'])
    op.create_index(op.f('ix_game_metrics_date'), 'game_metrics_daily', ['date'], unique=False)
    op.alter_column('game_metrics_daily', 'reviews_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_metrics_daily', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('game_metrics_daily', 'created_at')
    op.drop_column('game_metrics_daily', 'extras')
    op.drop_column('game_metrics_daily', 'wishlists')
    op.drop_column('game_metrics_daily', 'momentum_ratio')
    op.drop_column('game_metrics_daily', 'review_velocity_7d')
    op.drop_column('game_metrics_daily', 'reviews_30d')
    op.drop_column('game_metrics_daily', 'reviews_7d')
    # ### end Alembic commands ###