from apps.worker.tasks.collect_youtube_trends import *
from apps.worker.tasks.collect_youtube_comments import *
from apps.worker.tasks.analyze_youtube_trends import *
from apps.worker.tasks.generate_trend_queries import *
from apps.worker.tasks.collect_tiktok_trends import *
from apps.worker.tasks.collect_reddit_trends import *
from apps.worker.tasks.collect_twitter_trends import *
from apps.worker.tasks.analyze_reddit_trends import *
from apps.worker.tasks.save_daily_snapshot import *
from apps.worker.tasks.calculate_weekly_aggregates import *
